# Generated by Django 5.1.5 on 2025-02-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='Desc',
            field=models.CharField(max_length=100),
        ),
    ]
